### ISSUE TITLE
Windows环境下找不到opencv_core453.dll与lite.ai.tool.dll

### ISSUE THREAD

**Issue by WaterDhappy** [DefTruth/RobustVideoMatting-ncnn-mnn-tnn-onnxruntime#10]
您好，我在Windows环境下成功编译了lite.ai.toolkit ，
![@0 NW7{2))%~E V(Q~0EXB](https://user-images.githubusercontent.com/95896039/145678990-ed60c030-d9cc-46ec-bde7-181e0ee1e0dc.png)
但当我点击运行lite_rvm.exe时，提示我找不到opencv_core453.dll与lite.ai.tool.dll：
![image](https://user-images.githubusercontent.com/95896039/145679017-18f574d0-ae41-4101-89cc-1e1c4914f052.png)
![image](https://user-images.githubusercontent.com/95896039/145679022-ef20cd5e-15dc-4c72-9b30-5eaaac9a8e01.png)
 请问这个问题怎么解决？？十分感谢！

**Comment by DefTruth** [comment]
需要把opencv.dll和lite.ai.toolkit.dll放在exe的同一个目录下，否则会链接不到
