### ISSUE TITLE
你好，请问如何使用f16的模型？我使用f32的模型运行起来了， 但是速度不是特别理想，3060ti没占满，并且cpu只用到了单个核心

### ISSUE THREAD

**Issue by luckily-lzy** [DefTruth/RobustVideoMatting-ncnn-mnn-tnn-onnxruntime#2]
新手上路，不太会

**Comment by DefTruth** [comment]
> 新手上路，不太会

f16的模型现在直接调用有些问题，fp32没有问题，这里有讨论 #4 。GPU没有占满的原因，我想可能是我的这份实现里，暂时还没有实现C++版本的CUDA的io_binding。这个问题在RVM的官方仓库有说明，[inference_zh_Hans.md](https://github.com/PeterL1n/RobustVideoMatting/blob/master/documentation/inference_zh_Hans.md) . 您可以考虑在 [lite.ai.toolkit](https://github.com/DefTruth/lite.ai.toolkit) 中重新开这个issue，我会考虑在 [lite.ai.toolkit](https://github.com/DefTruth/lite.ai.toolkit) 中修复这个问题，因为这个demo 项目的c++实现是在[lite.ai.toolkit](https://github.com/DefTruth/lite.ai.toolkit) 中~ 
对于”cpu只用到了单个核心“，我想这应该是正常的，因为当你使用CUDA版本的时候，运算主要在GPU上。

**Comment by DefTruth** [comment]
> 新手上路，不太会

另外就是，如果你是用windows跑，可以参考 DefTruth/lite.ai.toolkit#10 进行GPU的兼容

**Comment by chris2lee** [comment]
> 刚上路，不太会
请问你有没有成功跑起来windows的GPU版本？
