### ISSUE TITLE
About Linux compile

### ISSUE THREAD

**Issue by LuoYingzhao** [DefTruth/RobustVideoMatting-ncnn-mnn-tnn-onnxruntime#7]
The lite.ai.toolkit has been build from Lite.AI.ToolKit. When build this RVM demo with only onnxruntime, it looks like that executable lite_rvm has beem built, but Segmentation fault comes from error of version? Some advice?

Attached below:

[100%] Linking CXX executable lite_rvm
[100%] Built target lite_rvm
Testing Start ...
The given version [9] is not supported, only version 1 to 8 is supported in this build.
Segmentation fault (core dumped)
Testing Successful !

**Comment by DefTruth** [comment]
I don't know why, it's seems that there was a problem with you gcc version, see similar problems:
https://github.com/catboost/catboost/issues/386  
I hope it helps ~

**Comment by LuoYingzhao** [comment]
Use "dmesg", the problem maybe come from the liblite.ai.toolkit.so.0.1.0.
When compile the lite.at.toolkit, the version requirements is opencv4.5.3 and onnxruntime1.7.0. Are there any other version requirements?

[1455575.521311] lite_rvm[36913]: segfault at 18 ip 00007ff2614d1348 sp 00007ffde15acbc0 error 4 in liblite.ai.toolkit.so.0.1.0[7ff2614a8000+63000]
