### ISSUE TITLE
win10上面是怎么部署的

### ISSUE THREAD

**Issue by pampasvbird** [DefTruth/RobustVideoMatting-ncnn-mnn-tnn-onnxruntime#8]
非常感谢作者做出这么有意义的内容，我在推广。现在有一个问题就是: 在win10上面, CMake后，一堆的找不到库。

**Comment by DefTruth** [comment]
这个仓库的代码只能在mac用。你可以尝试下把：https://github.com/DefTruth/lite.ai.toolkit 在windows下编译。可以参考 https://github.com/DefTruth/lite.ai.toolkit/blob/main/README.zh.md#lite.ai.toolkit-Build-Windows

**Comment by DefTruth** [comment]
> 非常感谢作者做出这么有意义的内容，我在推广。现在有一个问题就是: 在win10上面, CMake后，一堆的找不到库。

这里提供的是Mac的Demo，Linux和Win的版本需要重新编译toolkit，使用接口都是一样的。

**Comment by pampasvbird** [comment]
> > 非常感谢作者做出这么有意义的内容，我在推广。现在有一个问题就是: 在win10上面, CMake后，一堆的找不到库。
> 
> 这里提供的是Mac的Demo，Linux和Win的版本需要重新编译toolkit，使用接口都是一样的。

我理解了，那如果我要添加视频实时抠图, 改哪部分代码?在你的代码中, 直接 auto *rvm = new lite::cv::matting::RobustVideoMatting(onnx_path, 16);  这部分代码是 ai.toolkit封装掉的; 还是在外部改的; 编译你的ai.toolkit之前是不是我应该先设计这部分代码。

**Comment by DefTruth** [comment]
> > > 非常感谢作者做出这么有意义的内容，我在推广。现在有一个问题就是: 在win10上面, CMake后，一堆的找不到库。
> > 
> > 
> > 这里提供的是Mac的Demo，Linux和Win的版本需要重新编译toolkit，使用接口都是一样的。
> 
> 我理解了，那如果我要添加视频实时抠图, 改哪部分代码?在你的代码中, 直接 auto *rvm = new lite::cv::matting::RobustVideoMatting(onnx_path, 16); 这部分代码是 ai.toolkit封装掉的; 还是在外部改的; 编译你的ai.toolkit之前是不是我应该先设计这部分代码。

直接替换你编译好的动态库，在cmakelist设置好链接，这里的test_lite_rvm.cpp可以直接用。或者说你把编译好的库用到其他项目也是一样的，确保链接好就行。

**Comment by pampasvbird** [comment]
> 这个仓库的代码只能在mac用。你可以尝试下把：https://github.com/DefTruth/lite.ai.toolkit 在windows下编译。可以参考 https://github.com/DefTruth/lite.ai.toolkit/blob/main/README.zh.md#lite.ai.toolkit-Build-Windows

我发现你发给我的这个仓库中, 还是有很多的dylib...这个，不好意思, 新手真折腾人。真麻烦你。

**Comment by pampasvbird** [comment]
> > > > 非常感谢作者做出这么有意义的内容，我在推广。现在有一个问题就是: 在win10上面, CMake后，一堆的找不到库。
> > > 
> > > 
> > > 这里提供的是Mac的Demo，Linux和Win的版本需要重新编译toolkit，使用接口都是一样的。
> > 
> > 
> > 我理解了，那如果我要添加视频实时抠图, 改哪部分代码?在你的代码中, 直接 auto *rvm = new lite::cv::matting::RobustVideoMatting(onnx_path, 16); 这部分代码是 ai.toolkit封装掉的; 还是在外部改的; 编译你的ai.toolkit之前是不是我应该先设计这部分代码。
> 
> 直接替换你编译好的动态库，在cmakelist设置好链接，这里的test_lite_rvm.cpp可以直接用。或者说你把编译好的库用到其他项目也是一样的，确保链接好就行。

我就是想做成摄像头实时录制替换背景; 所以我就是想问这部分的代码在哪里改。不过目前为止，项目还没有跑开，好像问的有点远，

**Comment by DefTruth** [comment]
> > 这个仓库的代码只能在mac用。你可以尝试下把：https://github.com/DefTruth/lite.ai.toolkit 在windows下编译。可以参考 https://github.com/DefTruth/lite.ai.toolkit/blob/main/README.zh.md#lite.ai.toolkit-Build-Windows
> 
> 我发现你发给我的这个仓库中, 还是有很多的dylib...这个，不好意思, 新手真折腾人。真麻烦你。

dylib是mac下的动态库格式，win是dll，linux是so。我这里已经把一些需要用到的推理引擎(onnxruntime/MNN/NCNN/TNN)以及opencv打包在一起了，mac下可以直接跑。win还需要按照toolkit的README重新编译，包括编译opencv和对应的推理引擎。
