### ISSUE TITLE
可以公布一版Windows下能够成功运行的工程吗？

### ISSUE THREAD

**Issue by David-water** [DefTruth/RobustVideoMatting-ncnn-mnn-tnn-onnxruntime#9]

**Comment by DefTruth** [comment]
这个仓库的代码只能在mac用。你可以尝试下把：https://github.com/DefTruth/lite.ai.toolkit 在windows下编译。可以参考 https://github.com/DefTruth/lite.ai.toolkit/blob/main/README.zh.md#lite.ai.toolkit-Build-Windows

**Comment by DefTruth** [comment]
> 谢谢您的建议，如果从ONNXRuntime 和 OpenCV 官网上下载依赖库放入指定文件夹后，是否还需要再对lite.ai.toolkit进行编译呢？

是要的，因为这里编译好的lite.ai.toolkit.v.0.1.0.dylib是mac的动态库，不能在其他平台用。

**Comment by DefTruth** [comment]
> 谢谢您的建议，如果从ONNXRuntime 和 OpenCV 官网上下载依赖库放入指定文件夹后，是否还需要再对lite.ai.toolkit进行编译呢？

是要的，因为这里编译好的lite.ai.toolkit.v.0.1.0.dylib是mac的动态库，不能在其他平台用。

**Comment by David-water** [comment]
感谢您的帮助，我已成功编译lite.ai.toolkit。但当我点击运行lite_rvm.exe的时候，程序会自动闪退。请问有什么解决办法吗？

**Comment by DefTruth** [comment]
需要把opencv.dll和lite.ai.toolkit.dll放在exe的同一个目录下，否则会链接不到

**Comment by David-water** [comment]
我已经放到了同一目录，但依然存在点击exe后会闪退的问题。测试时发现此行代码可能是导致其闪退的原因，不知道怎么解决
`  auto *rvm = new lite::cv::matting::RobustVideoMatting(onnx_path,16); // 16 threads
`

**Comment by David-water** [comment]
经过修改，现在已经可以work了，感谢您的工作！

**Comment by Richardlyq** [comment]
> 经过修改，现在已经可以work了，感谢您的工作！

您好，请问能介绍一下您是怎么在windows下成功运行起来的吗
